# MYSQL_VER=5.7 docker compose -f ./docker/docker-compose.yml up --build
version: "2.4"
x-net:
  &net
  networks:
    - main
services:
  db:
    <<: *net
    image: datajoint/mysql:${MYSQL_VER}
    environment:
      - MYSQL_ROOT_PASSWORD=${DJ_PASS}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      retries: 5
      interval: 15s
networks:
  main:
